version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: venicars
      POSTGRES_USER: venicars
      POSTGRES_PASSWORD: venicars
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - ./docker/redis-data:/data

  osrm:
    image: ghcr.io/project-osrm/osrm-backend:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./docker/osrm-data:/data
    command: osrm-routed --algorithm mld /data/china-latest.osrm
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
